environment:

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.9"
      PYTHON_ARCH: "32"
      LIBGIT_VERSION: "0.24"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %LIBGIT_VERSION%"

install:
  - ".\\appveyor\\install_libgit.bat"
  - "%PYTHON%\\python setup.py build"
  - "%PYTHON%\\python setup.py test"

build: off
